server:
  port: 3001
spring:
  application:
    name: backend
  datasource:
    username: root
    password: momo0918
    url: jdbc:mysql://localhost:3306/book_crosser?useUnicode=true&characterEncoding=UTF-8&serverTimezone=PST&useSSL=false&useInformationSchema=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml